
local tasks_resources = {
    -- timeless = false,
    {
        group = "Life-changers",
        description = "Delete Fortnite",
        task_starts = "21:00",
        task_ends = "21:30",
        bg = "#fffeee",
        fg = "#000000",
    },
    {
        group = "Daily",
        description = "Meditate",
        task_starts = "08:00",
        task_ends = "08:10",
        -- bg = "#ffd000",
        -- bg = "#ffc800",
        bg = "#42b8ff",
        -- bg = "#fffdd8",
        -- fg = "#001f33",
        fg = "#000000",
    },
    {
        group = "Daily",
        description = "Record wannabe podcast",
        task_starts = "08:15",
        task_ends = "08:30",
        bg = "#ffc800",
        -- fg = "#3f1800",
        -- fg = "#000000",
        fg = "#000000",
    },
    {
        group = "Programming",
        description = "Write scrollable widget",
        task_starts = "08:35",
        task_ends = "10:00",
    },
    {
        group = "Habit",
        description = "Train",
        task_starts = "08:35",
        task_ends = "10:00",
    },
    {
        group = "habit",
        description = "grind",
        task_starts = "08:35",
        task_ends = "10:00",
    },
    {
        group = "Life-changers",
        description = "delete instagram",
        task_starts = "08:35",
        task_ends = "10:00",
    },
    {
        group = "Life-changers",
        description = "delete instagram again",
        task_starts = "08:35",
        task_ends = "10:00",
    },
    {
        group = "Programming",
        description = "Write scrollable widget",
        task_starts = "08:35",
        task_ends = "10:00",
    },
    {
        group = "Habit",
        description = "Train",
        task_starts = "08:35",
        task_ends = "10:00",
    },
}
return tasks_resources
